# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: vmConsole
description: >- # this means to ignore newlines until "baseurl:"
  Linux virtual machine for Android OS.
baseurl: "/vmConsole" # the subpath of your site, e.g. /blog
url: "https://sylirre.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site_source: "https://github.com/sylirre/vmConsole/tree/main/docs"
github_username:  sylirre

github: [metadata]

# Build settings
theme: minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: CommonMarkGhPages
commonmark:
  options: ["GITHUB_PRE_LANG", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "default"

feed:
  categories:
    - general

collections:
  posts:
    output: true
    permalink: /posts/:categories/:year/:month/:day/:title:output_ext

show_excerpts: true # set to true to show excerpts on posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
